### ISSUE TITLE
[use-with-antora] ui.supplemental_files block assumes that `node_modules` is in same directory as `antora-playbook.yml`

### ISSUE THREAD

**Issue by timo-a** [asciidoctor/asciidoctor-tabs#71]
I just tried to set up asciidoctor-tabs with antora with https://github.com/asciidoctor/asciidoctor-tabs/blob/main/docs/use-with-antora.adoc#using-the-supplemental-ui
 but got an error:

```` 
[me@mypc myproject]$ npx antora src/docs/config/antora-playbook.yml --stacktrace
[18:18:57.588] FATAL (antora): Failed to read ui.supplemental_files entry
    Cause: Error
        at transformError (/home/me/.npm/_npx/0d33774fda1fdb40/node_modules/@antora/ui-loader/lib/load-ui.js:408:22)
        at /home/t/.npm/_npx/0d33774fda1fdb40/node_modules/@antora/ui-loader/lib/load-ui.js:293:13
        at async Promise.all (index 1)
        at async GeneratorContext.loadUi (/home/me/.npm/_npx/0d33774fda1fdb40/node_modules/@antora/ui-loader/lib/load-ui.js:102:17)
        at async Promise.all (index 1)
        at async generateSite (/home/me/.npm/_npx/0d33774fda1fdb40/node_modules/@antora/site-generator/lib/generate-site.js:23:5)
        at async Command.parseAsync (/home/me/.npm/_npx/0d33774fda1fdb40/node_modules/commander/lib/command.js:935:5)
    Caused by: Error: ENOENT: no such file or directory, stat '/home/me/[...]/myproject/src/docs/config/node_modules/@asciidoctor/tabs/dist/css/tabs.css'
````
This is my project structure:

````
.
├── build.gradle.kts
├── node_modules
├── src
│   ├── docs
│   │   ├── adoc
│   │   │   ├── antora.yml
│   │   │   └── modules
│   │   │       └── ROOT
│   │   └── config
│   │       ├── antora-playbook.yml
│   │       └── build
│   ├── main
│   └── test
└── ...
```` 

The problem is that my node_modules folder is at top level, but my antora-playbook.yml is not, so the path at `content` is looking in `myproject/src/docs/config/node_modules`, when it should look in `myproject/node_modules`

````yaml
ui:
  supplemental_files:
  - path: css/vendor/tabs.css
    contents: ./node_modules/@asciidoctor/tabs/dist/css/tabs.css 
...
````
It works once I move my `node_modules` to `myproject/src/docs/config/`, but ideally I wouldn't have to.
Can the paths somehow be made more generic? Or at least a warning placed in the manual?

**Comment by mojavelinux** [comment]
I've added a note to the guide. No, I don't know how to make it more generic. If you do, I'd be glad to hear it.

If you are willing to an an Antora extension, it's possible to use it to register these supplemental files when Antora runs. The location of the files in the `@asciidoctor/tabs` package can be resolved using `require.resolve`.
